### ISSUE TITLE
e2e/temperature-events Milestone 1 flow

### ISSUE THREAD

**Issue by DavidBurela** [Azure-Samples/modern-data-warehouse-dataops#111]
End to end slice working, which doesn't require manually setting keys and secrets for each component.

- [ ]  IaC stamps out the infra, and stores the secrets & connection strings in KeyVault.
- [ ]  Deploy pipeline pushes AzFuncs, using Keyvault strings.
- [ ]  Run load test, using keyvault strings.
- [ ]  At this point can open App Insights and see things flowing through.

**Comment by DavidBurela** [comment]
Meant to leave this as a task
