### ISSUE TITLE
1.1 As a member of the dev team, I would like the ability to automatically provision infrastructure for Azure Databricks Service (Only Workspace)

### ISSUE THREAD

**Issue by namitms** [Azure-Samples/modern-data-warehouse-dataops#145]
I would like the ability to automatically provision infrastructure for Azure Databricks Service (Only Workspace)

# Acceptance criteria 
* Plain vanilla ADB workspace 
* Run the script manually (from Azure CLI)
* ARM Template for ADB
* Azure Keyvault and Storage account is provisioned as a part of the IAC deployment
* Keyvault - deployment owner should have rights for kv
* Keyvault - store PAT token, storage token
* Storage - LRS + hierarchical namespace

# Definition of done
* Resource group created if it doesn't already exist (seek user input)
* Script to provision an ADB workspace (with Keyvault and storage) is created, reviewed and checked-in
* Deployment script should ask user, or use env variables, for necessary input to deploy ADB service
* 3 ARM templates: ADB, Keyvault and Storage
* Readme file is updated with deployment instructions.
  * Environment 
  * Software/Hardware pre-requisites 

## Tasks
- [x] Arm template ramp up
- [x] ADB workspace ARM template (consider MSI and ADB Pat Token)
- [x] Key Vault ARM template (Add user from ADB/running user)
- [x] Storage Account ARM template (access from ADB workspace)
- [x] Script for deployment (local)
- [x] Investigate linting and validation extensions (devcontainer)
- [x] ~~Investigate compensated transactions~~ clean up step
- [x] Investigate `Bicep`
- [x] Update Documentation

**Comment by xinsnake** [comment]
@namitms @jsburckhardt  I'll take " Script for deployment (local)"

**Comment by jsburckhardt** [comment]
@xinsnake lets have a catch up for the script scope, variables and validation ?

**Comment by namitms** [comment]
Orchestration script

Log in to Azure, find the right information
Subscription
Resource Group / Region
Get ARM template parameters
Generate ARM template parameters from a “key”
Explicit passing in an ARM parameter file
Validate ARM templates in test resource group
Delete test resource group
Deploy templates
Check the resource is already there
Create ADB key in the Key Vault
Storage Account key in the Key Vault

**Comment by jsburckhardt** [comment]
ADB Pat Token will be part of the script orchestrator
