### ISSUE TITLE
Dev Investigation - Usage of Azure Blueprints within CSE/Fasttrack/CSU

### ISSUE THREAD

**Issue by namitms** [Azure-Samples/modern-data-warehouse-dataops#161]
Dev Investigation - Usage of Azure Blueprints within CSE/Fasttrack/CSU

# Questions:
- Seek input from CSU / CSE experience around their use of Azure Blueprints. How useful, what will this add to the project etc.

# Acceptance Criteria
* Research done to leverage Azure blueprints to develop the IAC sample for ADB

# Definition of done
* Documented inference of feasibility on leveraging Azure Blueprints

# Tasks
- [x] Feedback from CSU and WW community - @namitms 
  *  Inference captured [here](https://microsoft.sharepoint.com/teams/CSEFTEFY19/_layouts/OneNote.aspx?id=%2Fteams%2FCSEFTEFY19%2FShared%20Documents%2FCrew%20-%20Quokka%2FTeam%20Quokka&wd=target%28Product%20and%20Practise%20Contributions.one%7C406AD8E6-4EE8-458D-9B7D-07F1A161B8CD%2FAzure%20Blueprints%7C6A19F8AF-0E5E-4DAD-91D9-CAE20D3C174C%2F%29)
- [x] Feedback from, CSE - @Azadehkhojandi
- [ ] Feedback from Products and Domain experts - @devlace

**Comment by xinsnake** [comment]
@namitms  can you add some tasks to this ticket? Thanks!

**Comment by namitms** [comment]
> @namitms can you add some tasks to this ticket? Thanks!

Done
