### ISSUE TITLE
Include Unity Catalog into the E2E Databricks sample

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#765]
As a Data Engineer I would like to use the Unity Catalog on the Parking solution sample so I understand how it works and I don't need to work with the legacy Hive Metastore

**DoD**
- Successfully deploy and configure a Unity Catalog into the E2E Databricks + ADF sample
- All the tables should be generated under a "sensordata" metastore
- Hive metastore should not be used anymore
- Alter documentation accordingly

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

Top priority
-----------------------------------------------------------------
- [x] Modify ReadMe to reflect the pre-requisite of having a Regional Metastore - @thesqlpro  #978 
- [ ] Spike on impact of dbfs path change - @thesqlpro  + hemaverma (might be oof) #979 
- [ ] Change the import library process - ydaponte #980 
- [x] Upgrade Spark version to 15.4 LTS: @thesqlpro  #896  
- [x]  Research update creation of folder paths in ADLS to support Unity Catalog (POTENTIAL - might not be needed) @thesqlpro #981 

Ready to be picked up when team is available (most probably Sprint 5)
-----------------------------------------------------------------
- [x] Change Setup.py notebook - @thesqlpro #982 
- [x] Change/test Standardize and Transform notebooks @thesqlpro  #983 
- [x] Upgrade task of uploading Date/Time Dims to a notebook that creates them (deploy bash script) - @thesqlpro  #984 

Nice to Have
---------------------------------------------------------------------
- [ ] Document potential automation pieces (for future) for Unity Catalog #985 
- [ ] Create the Date/Time Dimensions programmatically in the SQL DB to remove reliance on Data file uploads (see #981 )

**Comment by thesqlpro** [comment]
Some notes from my research thus far:
Since Nov 2023 Unity Catalog is enabled by default (can check using this command in SQL editor SELECT CURRENT_METASTORE();)
Default name is the name of the workspace (inherited - although it looks like hyphens are converted to underscores) - this will need to be addressed
Default is in the region the workspace was created (Ex. WS created in EastUS2 then Metastore is in EastUS2)
By default a legacy Hive Metastore exists - will research if this can be removed or not, so far looks like it is included for backward compatibility

**Comment by thesqlpro** [comment]
The Catalog will be named **sensordata** to be more generic than parkingsensor.

**Comment by ydaponte** [comment]
Closing this issue as it is going to be replaced by #985
