### ISSUE TITLE
Databricks+ADF E2E Sample (Milestone 1)

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#782]
Milestone 1: mid-Jan.

## E2E Sample "Technical Problem"

- Technical Problem: Fix the ability for the sample to be deployed e2e and modernize sample with latest features from Databricks and ADF
- Persona: Data Engineers and Developers 

## IaC
- Fixing sample devcontainer
- Generate data that is independent from the public REST API (it can be re-used by the other E2E sample) and allowing batch and streaming modes to ingest the data
- Fixing bicep scripts that are failing with the latest versions and newer schemas (Synapse SQL Dedicated pool)
- Fixing broken main ./deploy.sh script when configuring the Databricks workspace for dev, stg and prod
- Upgrade to the latest Databricks CLI as the previous version is no longer working for certain parts of the code
- Incorporate the deployment of a Unity Catalog
- Fixing Key Vault Soft-Delete capability in the clean-up and deployment scripts
- Act on issues identified on the ISE Checklist (Other fundamentals)
- Document all changes, including architecture schemas when applicable
- [27.11.2014]. As we have more people contributing, we added some more improvements to the milestone as for example readme and guidance improvements, upgrading bicep versions used in the sample and replacing sql authentication by only entra id authentication.

## CI/CD
- Incorporate Asset Bundles to the CICD Databricks process
-  Act on issues identified on the ISE Checklist (Other fundamentals)
- Document all changes

## Security
- Start and act on the ISE Checklist on the Security pillar
- Document all changes
- Change SQL authentication by Entra only authentication

## Observability
-  Act on issues identified on the ISE Checklist (Observability)
- Document all changes, including architecture schemas when applicable

## Testing
- Document all changes, including architecture schemas when applicable

## Python Package modernization

For Package development, update to latest / best practices. Align with Fabric update team on python package modernization.

## VNext Milestone ideas: 

- Adding Autoloader to ingestion
- Adding Industry packages to the sample
- Add a dependency map of the versions across the sample
-----

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

## IaC
- [x] Fixing main issues: #817 
  - [x] Fix Dev container: #644 
  - [x] Fix Dev container: #646 
  - [x] Fix bicep scripts: #778 
  - [x] Fix main deployment script (ADB workspace): #630 
  - [x] Upgrade Databricks CLI: #763 
- [x] Fix clean-up script: #819 
  - [x] Key-vault soft delete: #596
  - [x] Delete based on deployment_id: #821 
- [x] Fix pipeline problems
   - [x] Fix ADF pipelines - temporary solution before #764 is ready: #852 
   - [x] Fix release pipelines: #864 
- [x] Remove REST API dependency: #764 
- [x] Incorporate Unity Catalog: #985 
Added on 27.11.2024 - as we have more contributors joining:
- [x] Fixing ReadMe, guidance and implementing usage and functionality improvements:
   - [x] Fix IMG folder dependency: #831 
   - [x] Upgrade bicep templates: #886 
   - [x] Remove CC SKU default reference: #885 
   - [x] Reduce deployment manual steps: #879 
   - [x] Review GitHub Enterprise guidance: #898 
   - [x] AzDO pipeline exists checks prior deployment: #881 
   - [x] SQL dedicated pool pause automated script: #882 
   - [x] Review GitHub Enterprise guidance: #898 

## CICD
- [ ] Incorporate Asset Bundles: #766 
- [ ] ISE Fundamentals Checklist: #841 - postponed
- [x] Automate manual publish in ADF: #897 

## Security
- [ ] ISE Security Checklist: #826 - ongoing, will continue on M2
- [x] Adding Keyvault secrets fail when value starts with an "-" hífen: #823 
- [x] Review complexity in random generated password: #824 
- [x] Change PAT token guidance to new granular version: #889 
- [x] Replace SQL Auth for Entra Auth only: #887 

## Observability
- [ ] ISE Observability Checklist: #839 - postponed

## Testing
- [POSTPONED to V2 ] Incorporate DFTF on ADF pipelines: #832 - - postponed to the M2 (as it is depending on the UC)
