### ISSUE TITLE
Fix main deployment issues

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#817]
As a Data Engineer, I want to be able to run the E2E Databricks + ADF sample with no errors so I can adapt the sample to my own requirements. 

**DoD**
- Dev container builds with no errors 
- Deployment script runs with no issues E2E
- Databricks new CLI is upgraded and functionality is fixed to perform the same functionality as before

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

- [ ] Fix Dev container: #644 
- [ ] Fix Dev container: #646 
- [ ] Avoid break in main script when opening Databricks workspace: #630 
- [ ] Fix bicep deployment Synapse dedicated pool: #778 
- [ ] Upgrade Databricks CLI #763 
- [ ] Ensure Databricks CLI is installed securely: #792
