### ISSUE TITLE
Miscellaneous fixes - sprint 2

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#822]
As a data engineer I want to run the E2E Databricks sample without random errors so I can continue to work on the functionality I require

**DoD**
- The random password string for the SQL pool is strong and complex enough, so the deployment won't fail
- Passwords generated to later be saved on the KeyVault should not start with an hífen "-" or the az cli command should be able to accept it
- Be able to login to the right tenant where the deployment should be done and change de documentation
- Be able to deploy the Spark cluster from bicep

This 2 items are transiting to the next sprint:
- Check AzDo pipeline existence prior creation and delete it to avoid failures if pipeline exists
- Incorporate an automated script that pauses all SQL dedicated pools in the subscription

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

- [x] Adding Keyvault secrets fail when value starts with an "-" hífen: #823 
- [x] Explicitly identify the tenant you are targeting for the deployment: #685 
- [x] Review complexity in random generated password: #824 
- [x] Install Spark cluster from bicep: #595 
- [x] Investigate the SP/mount issue: #642 

This 2 items are transiting to the next sprint:
- [ ] AzDO pipeline exists checks prior deployment: #881 
- [ ] SQL dedicated pool pause automated script: #882
