### ISSUE TITLE
ISE Observability Checklist

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#839]
The [ISE Checklist](https://aka.ms/isechecklist) is a tool that allows us to access Engineering fundamentals of an engagement from security, observability and responsible AI. 

**DoD**
- The checklist needs to be assessed and completed for: Observability.

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

**Observability** 
- [ ] Customer Conversation
- [ ] Customer Observability Level
- [ ] Auto-Instrumentation
- [ ] Basic Manual Instrumentation
- [ ] Dashboards
- [ ] Alerts
- [ ] Business-focused telemetry data
- [ ] Cost and Scale
