### ISSUE TITLE
ISE Engineering Fundamentals Checklist

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#841]
The [ISE Checklist](https://aka.ms/isechecklist) is a tool that allows us to access Engineering fundamentals of an engagement from security, observability and responsible AI. 

**DoD**
- The checklist needs to be assessed and completed for: Other Fundamentals.

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

**Engineering Fundamentals**
- [x] Governance  processes are put in place: Not applicable
- [x] Work Item Tracking (user stories, acceptance criteria, tasks, bugs): Implemented
- [x] MVEs have well defined hypothesis with clear metrics to accept or reject those hypothesis: Not applicable
- [x] Agile process is in place: Implemented
- [x] Source Control: Implemented
- [x] ADRs are available for most important decisions: Needs improvement
- [x] Code Reviews are taking place: Yes
- [ ] Testing: Started
  - [ ] Data pipelines Unit Testing: #832 (postponed for next Milestone)
- [x] CI/CD: Implemented
