### ISSUE TITLE
Miscellaneous improvements - sprint 3

### ISSUE THREAD

**Issue by ydaponte** [Azure-Samples/modern-data-warehouse-dataops#888]
As a data engineer I want to run the E2E Databricks sample with updated guidance and improved automation on the sample so I can continue to work on the functionality I require

**DoD**
- Create an img folder for the E2E Databricks + ADF to remove the dependency and avoid breaking changes on the other samples
- Upgrade bicep versions so warnings are not raised and the sample is using the last stable version available
- Remove Confidential Compute SKU as the default deployment
- Automate the ADF publishing option to remove manual dependency
- Replace SQL Auth by Entra Auth for SQL dedicated pool
- Improve guidance in the ReadMe for GitHub Enterprise guidance
- Remove root user dependency on the devcontainer
- Reduce manual steps on the deployment so that the azdo configuration is automated
- Verify azdo pipelines existence before re-deploying
- Fix issue with DevContainer for MAC users
- Investigate how to incorporate workload identities in AzDO pipelines
-  Define latest TLS on sql dedicated pool deploymentto 1.2
- Improving Log function 

Ensure you've read the [Contributing Guide (Microsoft Internal only.)](https://dev.azure.com/csedtd/_git/DataOps?path=%2FCONTRIBUTING.md&_a=preview)

- [ ] Remove root user in devcontainer: #825 
- [x] Fix IMG folder dependency: #831 
- [x] Upgrade bicep templates: #886 
- [ ] Remove CC SKU default reference: #885 
- [ ] Replace SQL Auth for Entra Auth only: #887 
- [x] Reduce deployment manual steps: #879 
- [x] Review GitHub Enterprise guidance: #898 
- [x] AzDO pipeline exists checks prior deployment: #881
- [ ] SQL dedicated pool pause automated script: #882 
- [x] Automate ADF publish: #897 
- [x] Fix DevContainer for MAC users: #918 
- [x] Workload Identity in AzDO pipelines investigation: #903  
- [x] Define latest TLS on sql dedicated pool deployment #940 
- [x] Improving Log function #929

**Comment by ydaponte** [comment]
The following issues will transit to the next sprint: 
#825 
#885 
#882 
#887
